---
title: pick-your-favourite
hero_image: images/banner.png
description: Create a fan website that gives users a choice of content
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Create the frame
- title: Choose your page colour
- title: Change some content
- title: Change the rest of the page
- title: Animate the sections
- title: Make the choice permanent
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Upgrade your project
- title: What next?
