---
title: Choisir ton favori
hero_image: images/banner.png
description: Crée un site web de fans qui offre aux utilisateurs un choix de contenu
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - title: Introduction
  - title: Créer le cadre
  - title: Choisir les couleurs de ta page
    completion:
      - engaged
  - title: Modifier du contenu
  - title: Modifier le reste de la page
  - title: Animer les sections
  - title: Rendre le choix permanent
    completion:
      - internal
  - title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet